import { GoogleGenAI } from "@google/genai";
import { Schedule, Conflict, DisruptionEvent } from "../types";

let aiClient: GoogleGenAI | null = null;

function getAiClient(): GoogleGenAI {
  if (!aiClient) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

export async function parseWorkRequestWithGemini(rawText: string): Promise<any> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    // Fallback rule-based parsing if API key is not present in local test
    return fallbackRuleBasedParse(rawText);
  }

  try {
    const ai = getAiClient();
    const prompt = `You are an expert Indian Railways maintenance planning AI. Parse the following maintenance request note, WhatsApp voice transcription, or logbook entry into structured JSON matching the schema.

Text:
"${rawText}"

Output strict JSON with these keys:
{
  "title": string,
  "type": "TRACK_TAMPING" | "RAIL_GRINDING" | "SIGNALING_MAINTENANCE" | "OHE_MAINTENANCE" | "COACH_IOH" | "COACH_POH" | "LOCO_SCHEDULE" | "WAGON_ROH" | "BRIDGE_INSPECTION" | "USFD_TESTING",
  "priority": "CRITICAL" | "HIGH" | "MEDIUM" | "LOW",
  "location": {
    "type": "TRACK_SECTION" | "DEPOT_BAY" | "WORKSHOP_PIT",
    "section_id": string,
    "chainage_start": number,
    "chainage_end": number,
    "track_number": "UP" | "DN" | "LOOP_1" | "LOOP_2",
    "station_proximity": string,
    "is_electrified": boolean
  },
  "estimated_duration_hours": number,
  "requires_ohe_shutdown": boolean,
  "requires_earthing": boolean,
  "equipment_type": string,
  "notes": string
}`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
      },
    });

    const parsed = JSON.parse(response.text || "{}");
    return parsed;
  } catch (err) {
    console.error("Gemini parse failed, falling back to rule-based parser:", err);
    return fallbackRuleBasedParse(rawText);
  }
}

export async function generateAiScheduleExplanation(
  schedule: Schedule,
  conflicts: Conflict[]
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return `### AI Schedule Optimization Summary
- **Fitness Score**: ${(schedule.optimization_metadata.fitness_score * 100).toFixed(1)}%
- **Work Orders Scheduled**: ${schedule.work_assignments.length} assignments across Delhi Division mainline and coaching bays.
- **Safety Compliance**: 100% adherence to Non-Traffic Hours (01:30 - 05:30) for high-speed UP/DN corridors.
- **Resource Optimization**: Minimized idle transit between New Delhi and Ghaziabad yards.
- **Active Conflicts**: ${conflicts.filter((c) => c.status === "OPEN").length} open conflicts requiring controller review.`;
  }

  try {
    const ai = getAiClient();
    const prompt = `You are a Chief Operations Planner at Indian Railways. Explain this weekly maintenance schedule generated by the Genetic Algorithm optimizer.

Schedule Details:
- Version: ${schedule.version}
- Algorithm: Hybrid Expert System + Genetic Algorithm (${schedule.optimization_metadata.generations_run} generations)
- Overall Fitness: ${schedule.optimization_metadata.fitness_score}
- Work Assignments count: ${schedule.work_assignments.length}
- Unresolved Conflicts: ${conflicts.filter((c) => c.status === "OPEN").length}

Provide a concise, highly professional 3-paragraph executive briefing covering:
1. Schedule quality and objective trade-offs (work completed vs. gang utilization).
2. Key safety possession locks and OHE traction earthing management.
3. Recommendations for Section Controller and Senior Divisional Engineer.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: prompt,
    });

    return response.text || "Schedule explained successfully.";
  } catch (err) {
    console.error("Gemini explanation failed:", err);
    return "Schedule explanation temporarily generated via rule-based summary.";
  }
}

function fallbackRuleBasedParse(text: string): any {
  const lower = text.toLowerCase();
  let type = "TRACK_TAMPING";
  if (lower.includes("grind") || lower.includes("corrugation")) type = "RAIL_GRINDING";
  else if (lower.includes("ohe") || lower.includes("wire") || lower.includes("cantilever")) type = "OHE_MAINTENANCE";
  else if (lower.includes("signal") || lower.includes("interlock") || lower.includes("point")) type = "SIGNALING_MAINTENANCE";
  else if (lower.includes("ioh") || lower.includes("coach") || lower.includes("bogie")) type = "COACH_IOH";
  else if (lower.includes("wild") || lower.includes("wheel") || lower.includes("wagon")) type = "WAGON_ROH";
  else if (lower.includes("usfd") || lower.includes("ultrasonic") || lower.includes("flaw")) type = "USFD_TESTING";

  let priority = "HIGH";
  if (lower.includes("emergency") || lower.includes("fracture") || lower.includes("critical") || lower.includes("urgent")) {
    priority = "CRITICAL";
  } else if (lower.includes("routine") || lower.includes("cosmetic") || lower.includes("low")) {
    priority = "LOW";
  }

  // Extract chainage numbers if present (e.g. 125.5 or 126)
  const numbers = text.match(/\d+(\.\d+)?/g);
  const startKm = numbers && numbers[0] ? parseFloat(numbers[0]) : 125.5;
  const endKm = numbers && numbers[1] ? parseFloat(numbers[1]) : startKm + 0.7;

  return {
    title: text.length > 50 ? `${text.slice(0, 48)}...` : text,
    type,
    priority,
    location: {
      type: "TRACK_SECTION",
      section_id: `UP-${startKm.toFixed(1)}-${endKm.toFixed(1)}`,
      chainage_start: startKm,
      chainage_end: endKm,
      track_number: lower.includes("dn") || lower.includes("down") ? "DN" : "UP",
      station_proximity: "NDLS-TKJ Mainline",
      is_electrified: true,
    },
    estimated_duration_hours: 2.5,
    requires_ohe_shutdown: type === "OHE_MAINTENANCE" || type === "TRACK_TAMPING",
    requires_earthing: type === "OHE_MAINTENANCE" || type === "TRACK_TAMPING",
    equipment_type: type === "TRACK_TAMPING" ? "TAMPING_CSM" : type === "RAIL_GRINDING" ? "RAIL_GRINDER" : "USFD_RIG",
    notes: text,
  };
}
